dist: trusty

language: bash

cache: 
  pip: true
  apt: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential curl git
  - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - export PATH="/home/travis/miniconda3/bin:$PATH"
  - bash bin/install/conda_env.sh
  - bash bin/install/from_src.sh
script:
  - source activate smsk_exfi
  - bash bin/simulate_dna.sh
  - snakemake -j
