# Travis config file
---
dist: trusty

language: bash

cache:
  pip: true
  directories:
    - $HOME/miniconda3_$TRAVIS_OS_NAME  # Add the installation to TRAVIS cache.
    - $HOME/download  # Sufficient to add miniconda.sh to TRAVIS cache.

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt_packages:
          - build-essential
          - git
          - curl
          - libboost-dev
          - gcc
          - autoconf
          - bzip2
          - zlib1g
          - libsparsehash-dev
          - cmake

before_install:
  - bash .travis/travis_before_install.sh

install:
  - export PATH="$HOME/miniconda3_$TRAVIS_OS_NAME/bin:$PATH"
  - bash .travis/travis_install.sh
  - conda install --yes -c bioconda snakemake

script:
  - echo $PATH
  - python3 --version
  - export PATH="$HOME/miniconda3_$TRAVIS_OS_NAME/bin:$PATH"
  - snakemake --use-conda -j

after_failure:
  - find results -name "*.log" -exec tail -vn +0 {} \; -exec echo -e "" \;
