dist: trusty

language: bash

sudo: required

cache:
  pip: true
  directories:
    - $HOME/miniconda3 # Add the installation to TRAVIS cache.
    - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.

addons:
    apt_packages:
      - build-essential
      - git
      - curl
      - libboost-dev

before_install:
  - bash .travis/travis_before_install.sh
  - export PATH="$HOME/miniconda3/bin:$PATH"

install:
  - bash src/install/conda_env.sh
  - bash src/install/from_src.sh
  - export PATH="$PWD/bin:$PATH"

script:
  - source activate exfi_validation
  - bash src/simulate_dna.sh
  - snakemake -j
