dist: trusty

language: bash

cache:
  pip: true
  directories:
    - $HOME/miniconda3_$TRAVIS_OS_NAME # Add the installation to TRAVIS cache.
    - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt_packages:
          - build-essential
          - git
          - curl
          - libboost-dev
          - gcc
          - autoconf
          - bzip2
          - zlib1g
          - libsparsehash-dev

before_install:
  - bash .travis/travis_before_install.sh
  - export PATH="$HOME/miniconda3_$TRAVIS_OS_NAME/bin:$PATH"

install:
  - bash src/install/conda_env.sh
  - source activate exfi_validation
  - bash src/install/from_src.sh
  - export PATH="$PWD/bin:$PATH"

script:
  - echo $PATH
  - python3 --version
  - bash src/simulate_dna.sh
  - snakemake -j

after_failure:
  - find results -name "*.log" -exec tail -vn +0 {} \; -exec echo -e "" \;
