samples:
    dna1:
        forward: data/reads/dna1_1.fq.gz
        reverse: data/reads/dna1_2.fq.gz
        molecule: dna
        type: PE
        phred: phred33
        adaptor: data/adaptors/TruSeq3-PE-2.fa
    dna2:
        forward: data/reads/dna2_1.fq.gz
        reverse: data/reads/dna2_2.fq.gz
        molecule: dna
        type: PE
        phred: phred33
        adaptor: data/adaptors/TruSeq3-PE-2.fa

assembly:
    data/reference/transcriptome.fa

reference:
    exome:
        data/reference/exome.fa
    transcriptome:
        data/reference/transcriptome.fa
    genome:
        data/reference/genome.fa
    annotation:
        data/reference/annotation.gff3

exfi:
    kmer: "27"
    levels: "1"
    size: "500M"
    max_fp_bases: "5"
    max_overlap: "10"
    max_gap_size: "10"
    gfa1_to_exons_extra: "--soft-mask-overlaps"
    gfa1_to_gapped_transcript_extra: "--soft-mask-overlaps"

pr:
    fraction_overlap: 0.9
