samples:
    dna1:
        forward: data/reads/dna1_1.fq.gz
        reverse: data/reads/dna1_2.fq.gz
        molecule: dna
        type: PE
        phred: phred33
        adaptor: data/adaptors/TruSeq3-PE-2.fa
    dna2:
        forward: data/reads/dna2_1.fq.gz
        reverse: data/reads/dna2_2.fq.gz
        type: PE
        molecule: dna
        type: PE
        phred: phred33
        adaptor: data/adaptors/TruSeq3-PE-2.fa

assembly:
    data/reference/transcriptome.fa

reference:
    exome:
        data/reference/exome.fa
    transcriptome:
        data/reference/transcriptome.fa
    genome:
        data/reference/genome.fa

exons:
    kmer: "27"
    levels: "1"
    size: "500M"
    trim_left: 1
    trim_right: 1


